name: args_generator_annotations
description: Args Generator - A code generator for Flutter page arguments
version: 1.2.5
homepage: https://github.com/yelmuratoff/args_generator
repository: https://github.com/yelmuratoff/args_generator

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies: {}

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  args_generator: ^1.2.5

dependency_overrides:
  args_generator:
    path: ../../
