name: page_args_generator_example
description: A sample command-line application.
version: 1.1.0
homepage: https://github.com/yelmuratoff/args_generator
repository: https://github.com/yelmuratoff/args_generator

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  args_generator_annotations: ^0.0.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.14
  args_generator: ^0.0.9

dependency_overrides:
  args_generator_annotations:
    path: ../packages/args_annotations
  args_generator:
    path: ../
