name: args_generator
description: Page Args Generator - A code generator for Flutter page arguments
version: 1.2.0
homepage: https://github.com/yelmuratoff/args_generator
repository: https://github.com/yelmuratoff/args_generator

executables:
  args_generator:

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  build: ^2.5.4
  analyzer: ^7.4.6
  collection: ^1.19.1
  source_gen: ^2.0.0
  args_generator_annotations: ^1.2.0
  glob: ^2.1.3

dev_dependencies:
  build_runner: ^2.5.4
  lints: ^6.0.0
  test: ^1.26.2

dependency_overrides:
  args_generator_annotations:
    path: packages/args_annotations
