name: args_generator
description: Page Args Generator - A code generator for Flutter page arguments
version: 1.1.0
homepage: https://github.com/yelmuratoff/args_generator
repository: https://github.com/yelmuratoff/args_generator

executables:
  args_generator:

environment:
  sdk: ^3.6.0

dependencies:
  build: ^2.4.2
  analyzer: ^6.5.0
  collection: ^1.19.0
  source_gen: ^1.5.0
  args_generator_annotations: ^1.1.0
  glob: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.1.1
  test: ^1.25.14

dependency_overrides:
  args_generator_annotations:
    path: packages/args_annotations
